name: CI

on:
  schedule:
    - cron: '0 14 * * *'
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow'
        required: true
        default: 'main'
        options:
          - main
          - develop
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'prd'
        options:
          - tst
          - hlg
          - prd

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: |
          npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --config video=true --env allure=true

      - name: Generate Allure Report
        run: |
          curl -o allure-commandline.zip -L "https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.9/allure-commandline-2.13.9.zip"
          unzip -o allure-commandline.zip -d allure
          export PATH=$PATH:$PWD/allure/allure-2.13.9/bin
          allure generate allure-results --clean -o allure-report
          mv -f allure-report/history allure-results/history
          allure generate allure-results --clean -o allure-report
  
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          publish_dir: ./allure-report
